### ISSUE TITLE
TYPESCRIPT: Error invalid node type at position 3324

### ISSUE THREAD

**Issue by dominikhaid** [nvim-treesitter/nvim-tree-docs#14]
Typescript often throws the following error:

`Error executing vim.schedule lua callback: .../start/navigator.lua/lua/navigator/lspclient/clients.lua:343: Vim(lua):E5108: Error executing lua ...are/nvim/share/nvim/runtime/lua/vim/treesitt
er/query.lua:161: query: invalid node type at position 3324
`
Error is always on 3324 and happens only in pure ts files tsx is not erring, sadly gdd works in none of both.

Note: I done the ansiseed fix

**Comment by juanramirezc2** [comment]
I'm facing this issue too. it seems like the queries this extension is generating are not valid grammar for typescript parser

**Comment by steelsojka** [comment]
I believe some nodes changed names or were removed since the queries were
written. Ill have to hunt down which one it is.

**Comment by steelsojka** [comment]
This is fixed in the latest master.

**Comment by juanramirezc2** [comment]
Thank you @steelsojka 🥳
