### ISSUE TITLE
Aniseed not found

### ISSUE THREAD

**Issue by Mte90** [nvim-treesitter/nvim-tree-docs#9]
I am getting this error with the latest neovim compiled version:

```^Ino field package.preload['aniseed.core']
^Ino file './aniseed/core.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/luajit-2.1.0-beta3/aniseed/core.lua'
^Ino file '/usr/local/share/lua/5.1/aniseed/core.lua'
^Ino file '/usr/local/share/lua/5.1/aniseed/core/init.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/lua/5.1/aniseed/core.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/lua/5.1/aniseed/core/init.lua'
^Ino file './aniseed/core.so'
^Ino file '/usr/local/lib/lua/5.1/aniseed/core.so'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/lib/lua/5.1/aniseed/core.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './aniseed.so'
^Ino file '/usr/local/lib/lua/5.1/aniseed.so'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/lib/lua/5.1/aniseed.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
.../plugged/nvim-tree-docs/lua/nvim-tree-docs/collector.lua:31: attempt to index local '_local_0_' (a nil value)
Failed to load:  /home/mte90/.config/nvim/lua/plugin/ts.lua
^I ...m/plugged/nvim-tree-docs/lua/nvim-tree-docs/internal.lua:31: attempt to index local '_local_0_' (a nil value)```

**Comment by goncalves-diogo** [comment]
I've also had a similar issue. From what I've seen about the plugin it has a dependency from [aniseed](https://github.com/Olical/aniseed)

In order to solve the issue try to install aniseed as such

```
    " Dependecy
    Plug 'Olical/aniseed', { 'tag': 'v3.19.0' }
    Plug 'nvim-treesitter/nvim-tree-docs'

```
Note: I'm a newbie about this still, sorry if i gave you shit advice xD

**Comment by Mte90** [comment]
I confirm that fix but I don't see https://github.com/nvim-treesitter/nvim-tree-docs/issues/8
I think that the plugin is not executed maybe?

**Comment by Olical** [comment]
You can try [this fork](https://github.com/Olical/nvim-tree-docs) where I've updated Aniseed and corrected the references to the embedded library so you don't need to have it installed globally.

I'll create a PR too.

**Comment by Olical** [comment]
You shouldn't need to install Aniseed yourself since it's bundled with the plugin automatically, some references / requires just needed updating.

**Comment by dominikhaid** [comment]
Replacing ansiseed with  nvim-tree-docs.aniseed.core worked for me, at least JavaScript works now.
